name: shelf_request_response_2_jsonable_object_utility
description: A utility that converts the json request body to a jsonable type and one from a jsonable to a response
version: 1.0.1
homepage: https://github.com/RafaelSilvaPereira/shelf_request_response_2_jsonable_object_utility

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  jsonable_object: ^1.0.1
  shelf: ^1.2.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
